### ISSUE TITLE
netcdf and plotting problems for io_sst.load()

### ISSUE THREAD

**Issue by finnlindgren** [fbachl/inlabru#10]
io_sst.load() as used by the example for sst() fails at plot(sst) with error
`> sst = io_sst.load(year=c(2006,2007))`
`> plot(sst)`
`Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'`
due to sst in plot(sst) being a list. Unclear what it expected it to be.

Also, is_sst.load require RNetCDF which should therefore be listed in Imports: in DESCRIPTION, and requireNamespace() used instead of require() (a couple of versions back R changed the depends/imports/namespace system, so old code and recommendations are now incorrect even if they sometimes work).  Even better would be to also replace it with the ncdf4 package, which doesn't require the user to install a libudunits2-dev package (or equivalent), but only the netcdf development files.

**Comment by fbachl** [comment]
All ETP related code has been removed from inlabru, including the SST code.
