### ISSUE TITLE
Spatio-temporal marked point pattern - Error in ibm_n.default(x[["mapper"]]) 

### ISSUE THREAD

**Issue by iparperspective** [fbachl/inlabru#134]
Hi,

I am relatively new to inlabru and I am trying to fit a Marked point pattern that evolves in time (a preferential sampling problem). Is it possible?

When I fit the models separately, the code runs smoothly. It is when I join both and fit them together that I get the following error:

_Error in ibm_n.default(x[["mapper"]]) : 
  Default 'ibm_n()' method called but mapper doesn't have an 'n' element._

This is the code I am using:

ips <- ipoints(mesh, group = "time")
matern <- inla.spde2.pcmatern(mesh, ...)

cmp = ~ mySmooth(coordinates, model = matern, group = time, ngroup = 4) +
  mySmoothcCopy(coordinates, copy = "spde", fixed = FALSE) +
  CpIntercept(1) +
  Intercept(1)

lik1 <- like(data =  spdf,
             family = "gamma",
             formula = CPUE ~ mySmooth + Intercept)
lik2 <- like(data =  spdf,
             family = "cp",
             ips = ips,
             formula = coordinates + time~ mySmoothCopy + CpIntercept)
fit <- bru(components = cmp, lik1, lik2)

**Comment by finnlindgren** [comment]
Can you construct a test case with a constructed toy data set, e.g. with a subset of your data?
I haven’t tested grouped models with copy, but I think you need to supply group=time to the copy component as well, so it known for what time points to evaluate the copy.

Finn

**Comment by finnlindgren** [comment]
But the error message indicates there may be more than one issue.

**Comment by iparperspective** [comment]
Hi,

Maybe best if I supply a subset of the data and code. 
Here's a link to it: https://www.dropbox.com/sh/julit2m1jipsy97/AAD_D5B_gfG4IRFZADEBaYDKa?dl=0

Thank you for your time!
iosu

**Comment by finnlindgren** [comment]
First issue: you need `copy = "mySmooth"` instead of `copy = "spde"`; it should be the name of the component being copied.
But after fixing that problem there's a further issue that I'm now debugging.

**Comment by finnlindgren** [comment]
Corrected component definitions:
```r
cmp = ~ mySmooth(coordinates, model = matern, group = tiempo, ngroup = 4) +
  mySmoothCopy(coordinates, copy = "mySmooth", group = tiempo, fixed = FALSE) +
  CpIntercept(1) +
  Intercept(1)
```
(Note: linked to #57 )
