### ISSUE TITLE
Feature: distance sampling for Poisson

### ISSUE THREAD

**Issue by dmi3kno** [fbachl/inlabru#209]
I am trying to implement the model, where I have the aggregated counts on a grid. Some counts are low (or even missing) because they are undersampled. I wanted to implement a distance sampling algorithm, but then I discovered that `samplers` argument is only defined for `family="cp"`.

Literature:
- [Royle et al (2004)](http://doi.wiley.com/10.1890/03-3127) "Modeling abundance effects in distance sampling"
- [Eberhardt (1967)](https://doi.org/10.2307/2528156). "Some Developments in 'Distance Sampling'"
- [Miller et al (2013)](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12105) "Spatial models for distance sampling data: recent developments and future directions", section "Count as response" 

How do I adjust for "distance to road" if I have total counts per pixel? I could, of course, turn my Pixel counts into an LGCP by uniformly distributing the points within each cell, but it feels wrong to do so.

Here's an example of implementation [in INLA](https://github.com/jorgesicacha/VSE-paper/blob/f9b70e4e27300fec6bf18700b754ce30f6a970f5/MooseExample/MooseExampleNew.R#L219C76-L219C130)

**Comment by finnlindgren** [comment]
If you precompute the "distance to road" at the grid locations and add them as `distance` in the data data.frame, you can use them in the predictor expression in the same way as in the transect distance sampling case.
```
formula <- observed_counts ~ some + component + combination + log_detection_probability(dist, some, parameters)
```
The `cp` model uses `domain` and `samplers` to call `fm_int(domain = domain, samplers = samplers)`, but in your case you already have all the required information, so there's no need to create any extra integration points.
