### ISSUE TITLE
Example in `generate` function is duplicated

### ISSUE THREAD

**Issue by PPaccioretti** [fbachl/inlabru#231]
The example for the `generate` function is duplicated in the bru.inference.R file. It appears twice, once on [on line 16](https://github.com/inlabru-org/inlabru/blob/4d710e01f9fed27dfb2f9bfccd3892c42b361ee9/R/bru.inference.R#L16) and again on line [on line 2174](https://github.com/inlabru-org/inlabru/blob/4d710e01f9fed27dfb2f9bfccd3892c42b361ee9/R/bru.inference.R#L2174C2-L2174C41). 
AFAIK, the reason that the examples are duplicated is that roxygen merges them when you use `#' @rdname generate`  in line [2175](https://github.com/inlabru-org/inlabru/blob/4d710e01f9fed27dfb2f9bfccd3892c42b361ee9/R/bru.inference.R#L2175), so deleting one should be enough to fix this issue.

**Comment by finnlindgren** [comment]
Thanks! They were probably documented separately at some point and this wasn’t noticed when they were merged.
