### ISSUE TITLE
Error with predict function running St Andrews workshop code

### ISSUE THREAD

**Issue by luisabaker** [fbachl/inlabru#54]
The workshop code including the pre-Workshop inlabru installation test code keeps giving me the following error with the predict function

> Error in samples[[i]] : subscript out of bounds
In addition: Warning message:
In inla.posterior.sample.interpret.selection(selection, result) :
  Some selections are not used:

This error occurs with both the CRAN and development versions of inlabru and both the gorillas and Poisson2_1D datasets. R console output including session info is attached. Am I doing something wrong?

[R_console_output_inlabru.txt](https://github.com/fbachl/inlabru/files/2624850/R_console_output_inlabru.txt)

**Comment by finnlindgren** [comment]
This has been fixed on the devel branch (commit daa16cd)
