### ISSUE TITLE
Different results fitting same model using inlabru vs INLA

### ISSUE THREAD

**Issue by ASeatonSpatial** [fbachl/inlabru#83]
I'm trying to refit an INLA model using inlabru and getting very different results.  The INLA model
was written by a colleague and it's predictions look pretty sensible.  I'm not getting good results trying to do the same with inlabru.  

It's quite possible I think I'm fitting the same model but that I actually am doing something different in the inlabru case.  The main difference in the code is for inlabru I don't do any stacks with NAs for prediction since there are `predict` methods for inlabru models.  

Here is my code:

```R
require(gamair)   # has aral sea chlorophyll data
data(aral)
data(aral.bnd)
library(inlabru)
library(INLA)

# Mesh stuff
bnd <- inla.mesh.segment(cbind(aral.bnd$lon, aral.bnd$lat))
loc <- cbind(aral$lon, aral$lat)

## Build the mesh:
mesh <- inla.mesh.2d(boundary=bnd,
                     max.edge=c(0.384, 0.5),
                     min.angle=c(30, 21),
                     max.n=c(48000, 16000), ## Safeguard against large meshes.
                     max.n.strict=c(128000, 128000), ## Don't build a huge mesh!
                     cutoff=0.01, ## Filter away adjacent points.
                     offset=c(0.1, 0.3)) ## Offset for extra boundaries, if needed.


# spde model - same for both inlabru and INLA models

spde <- inla.spde2.pcmatern(mesh=mesh,
                            prior.range=c(0.1, 0.1),
                            prior.sigma=c(4, 0.1))


# inlabru fit
# -----------

formula <- chl ~ Intercept + grf(main = c("lon", "lat"), model=spde)

fit_inlabru <- bru(formula,
                  family = "gaussian",
                  data = aral)

> range(fit_inlabru$summary.random$grf$mean)  
[1] -0.0003969954 -0.0001473630

# spde not very different from zero

# INLA fit
# --------

xx <- as.matrix(aral[,c("lon", "lat")])
Xp <- inla.spde.make.A(mesh, xx)

# setup estimation stack
stk.e <- inla.stack(tag='est', ## tag
                    data=list(chl=aral$chl), ## response
                    A=list(Xp),  
                    effects=list(s=1:spde$n.spde))

# setup prediction stack 
stk.p <- inla.stack(tag='pred', ## tag
                    data=list(chl=NA), ## response NA, to predict
                    A=list(Xp),
                    effects=list(s=1:spde$n.spde))

# stack the stacks
stk.full <- inla.stack(stk.e, stk.p)

formula <- chl ~ f(s, model = spde)

fit_inla <- inla(formula,
                 data=inla.stack.data(stk.full),
                 control.predictor=list(A = inla.stack.A(stk.full),
                                        compute=TRUE),
                 control.compute=list(config = TRUE))

> range(fit_inla$summary.random$s$mean)     
[1] -3.760937  8.507071    
# spde different from zero (this model looks okay when you plot predictions 
# alongside the data)
```
my session info is:

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] INLA_20.10.12-1    foreach_1.5.1      Matrix_1.2-18      inlabru_2.1.14.900
[5] sp_1.4-4           ggplot2_3.3.2      gamair_1.0-2      

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11    magrittr_1.5       splines_4.0.3      tidyselect_1.1.0  
 [5] munsell_0.5.0      colorspace_1.4-1   lattice_0.20-41    R6_2.4.1          
 [9] rlang_0.4.8        dplyr_1.0.2        tools_4.0.3        rgdal_1.5-18      
[13] grid_4.0.3         gtable_0.3.0       withr_2.3.0        MatrixModels_0.4-1
[17] iterators_1.0.13   ellipsis_0.3.1     yaml_2.2.1         tibble_3.0.4      
[21] lifecycle_0.2.0    crayon_1.3.4       purrr_0.3.4        codetools_0.2-16  
[25] vctrs_0.3.4        glue_1.4.2         compiler_4.0.3     pillar_1.4.6      
[29] generics_0.0.2     scales_1.1.1       pkgconfig_2.0.3 
```

**Comment by finnlindgren** [comment]
I get a warning for the bru call,
`## Warning in storage.mode(A) <- "double": NAs introduced by coercion`
I'll check if this is the root cause of the problem.

For the the inla version, you should use an explicit intercept to ensure the stack does what you intend. inla should give you a warning, that I do see:
```
## Warning in inla(formula, data = inla.stack.data(stk.full), control.predictor = list(A = inla.stack.A(
## but an intercept is in the formula. This will likely result
## in the intercept being applied multiple times in the model, and is likely
## not what you want. See ?inla.stack for more information.
## You can remove the intercept adding ``-1'' to the formula.
```
To fix the latter issue, change to this:
```
stk.e <- inla.stack(tag='est', ## tag
                    data=list(chl=aral$chl), ## response
                    A=list(Xp),
                    effects=list(list(s=1:spde$n.spde, Intercept = 1)))

# setup prediction stack
stk.p <- inla.stack(tag='pred', ## tag
                    data=list(chl=NA), ## response NA, to predict
                    A=list(Xp),
                    effects=list(list(s=1:spde$n.spde, Intercept = 1)))

# stack the stacks
stk.full <- inla.stack(stk.e, stk.p)

formula <- chl ~ -1 + Intercept + f(s, model = spde)
```
However, in your example this doesn't have any major effect on the output, so it's likely related to the first warning.

**Comment by finnlindgren** [comment]
You're using an unsupported syntax to access the coordinates. Currently, this is your easiest option:
```
formula <- chl ~ Intercept + grf(main = coordinates, model=spde)

library(sp)
aral_sp <- aral
coordinates(aral_sp) <- c("lon", "lat")
# coordnames(aral_sp) <- c("x", "y") # Some of the code requires coordinates to be names x and y, but in this case the original names seem to be ok; lgcp() models are the likely case to need x and y until those parts of the code are corrected to allow arbitrary names
fit_inlabru <- bru(formula,
                   family = "gaussian",
                   data = aral_sp)
```
Result:
```
range(fit_inlabru$summary.random$grf$mean)
[1] -3.752640  8.515154
```

**Comment by ASeatonSpatial** [comment]
Strange that I get neither of the warnings when I run that code.  

Good to know that about the coordinates, ideally would be nice not to use `sp` unless necessary but this works.

**Comment by finnlindgren** [comment]
Yes, I wondered about that. It's possible that the new factor support code is too clever, so that you ended up indexing the first two mesh nodes only, or something similar.

The original internal code for spatial support was built entirely around sp. Another effort is needed to clean up the internal mapping code to modularise it to allow e.g. sf support as well, but one of the aims of the new internal rewrite was to make it easier to add different type of mapping methods, so when the update is done we can start looking at that.

Something with general R code like `main = as.matrix(data[,c("lon", "lat"),drop=FALSE])` might even work already, if I've remembered to make the data object visible to the mapping environment (I recall thinking of what name should be used to make it visible, but I'm not sure if I reached a conclusion).

**Comment by finnlindgren** [comment]
You should definitely get the _second_ warning, about intercepts. Do you have some setting that disables warnings?

**Comment by ASeatonSpatial** [comment]
Unfortunately I get a new error.  Possibly related to the recent changes to proj ?

```R
formula <- chl ~ Intercept + grf(main = coordinates, model=spde)

aral_sp <- aral
coordinates(aral_sp) <- c("lon", "lat")
fit_inlabru <- bru(formula,
                   family = "gaussian",
                   data = aral_sp)
```

gives me

```
Error in slot(x, "proj4string") : 
  no slot of name "proj4string" for this object of class "CRS"
```

**Comment by ASeatonSpatial** [comment]
I recently reinstalled R to upgrade to 4.0 and reinstalled INLA and inlabru.  I don't remember doing anything about warnings

**Comment by finnlindgren** [comment]
You have the same sp, rgdal, and gamair versions as I do, so that shouldn't be the problem. Since I've been working on sp related stuff recently, can you check with the very latest inlabru devel version?

**Comment by finnlindgren** [comment]
Also, the error message doesn't tell me where the error was. Please provide `traceback()` info as well.

**Comment by ASeatonSpatial** [comment]
Will update from devel branch just now.  

Traceback:

```> traceback()
18: slot(x, "proj4string")
17: comment(slot(x, "proj4string"))
16: is.na.CRS(crs)
15: is.na(crs)
14: crs_is_null(data_crs)
13: input_eval.bru_input(subcomp$input, data = lh$data, env = env, 
        label = subcomp$input$label, null.on.fail = TRUE)
12: input_eval(subcomp$input, data = lh$data, env = env, label = subcomp$input$label, 
        null.on.fail = TRUE)
11: FUN(X[[i]], ...)
10: lapply(lhoods, function(lh) input_eval(subcomp$input, data = lh$data, 
        env = env, label = subcomp$input$label, null.on.fail = TRUE))
9: add_mapper(component$main, label = component$label, lhoods = lh, 
       env = component$env)
8: add_mappers.component(components[[k]], lhoods)
7: add_mappers(components[[k]], lhoods)
6: add_mappers.component_list(components, lhoods = lhoods)
5: add_mappers(components, lhoods = lhoods)
4: component.formula(components, lhoods)
3: component(components, lhoods)
2: make.model(components, lhoods)
1: bru(formula, family = "gaussian", data = aral_sp)
```

**Comment by finnlindgren** [comment]
I've just pushed a small update related to the code in your error; I'm not sure why I didn't get an error on my side, but let me know if this very latest version solves it.

**Comment by ASeatonSpatial** [comment]
Seems fine on most recent devel branch.  
A TODO message appears now.  

```
> fit_inlabru <- bru(formula,
+                    family = "gaussian",
+                    data = aral_sp)
TODO: Ensure spatial input objects use the same CRS

> range(fit_inlabru$summary.random$grf$mean)
[1] -3.752638  8.515147
```

I also tried 

```
formula <- chl ~ Intercept + grf(main = as.matrix(data[,c("lon", "lat"),drop=FALSE]),
                                 model=spde)
```

just to see, but got the same results as with `c("lon", "lat)`.

**Comment by finnlindgren** [comment]
OK; the TODO message should have been there in your previous version as well, so not sure what's going on with that, but good that the latest version seems OK.
The TODO messages are reminders for me, and can be ignored. They'll disappear when I get to fix those parts of the code. This message is for a sanity check that the user has supplied a coherent set of data inputs (it could in theory allow different CRSes, but it would make the internal code much messier).

**Comment by ASeatonSpatial** [comment]
It maybe just never reached the TODO stage because it hit the error.  I'll look into this INLA warning as well and bring it up with the R-INLA help.  My global warnings option is not set to suppress anything, not sure what's going on with that.

**Comment by finnlindgren** [comment]
The missing INLA Intercept warning is odd, and hard to reproduce, since I get the warning when running your code...

**Comment by finnlindgren** [comment]
This works, without involving sp:
```
aral_coord <- aral[,c("lon", "lat"), drop=FALSE]
formula <- chl ~ Intercept + grf(main = aral_coord, model=spde)

fit_inlabru <- bru(formula,
                   family = "gaussian",
                   data = aral)
```
For point processes, the `main=` input is constructed internally, so there the `sp`&`coordinates` approach is needed, but for georeferenced data the above works.

**Comment by finnlindgren** [comment]
It would be useful to get suggestions for how you would _like_ to be able to specify the coordinate information with non-`sp` methods. Ideally, e.g. `sf` might have classes similar to `SpatialPoints/Pixels/Grid/DataFrame`?

**Comment by finnlindgren** [comment]
Also note that the non-sp `aral_coord` approach will likely run into problems if running a multi-likelihood model; for that, I need to allow access to the internal data object to the `main=` R expressions.

**Comment by finnlindgren** [comment]
I had forgotten to check the obvious (in hindsight) solution:
```
formula <- chl ~ Intercept + grf(main = cbind(lon, lat), model=spde)
fit_inlabru <- bru(formula,
                   family = "gaussian",
                   data = aral)

range(fit_inlabru$summary.random$grf$mean)
# [1] -3.752640  8.515154
```
This works because main parses a general R expression, and while the full data object might not currently be available to it, it does have the actual variables of the input `data.frame`.

**Comment by ASeatonSpatial** [comment]
That works for me.  Would this work with `lgcp()` ? 

It's hard to think of a general syntax that would work for data.frame, sf and sp but  I think with good documentation a few different options could be used.  Maybe accept a vector with strings that are the relevant column names in the data object? I think this was my attempt because it felt natural in some way.  If `coordinates` is used then do appropriate things depending on whether it is `sp` or `sf`?  I think it would be odd to require different syntax of the user for these two cases since internally functions could be written to extract the relevant information from the spatial objects.  

The `coordinates` syntax I always felt was a strange one to be hardcoded.    Out of interest, where is the documentation for these things?  In INLA I would do `?f` and start from there, not sure it's clear how to find out what `main=` and `model=` should be in inlabru.

**Comment by ASeatonSpatial** [comment]
There's not much wrong with `cbind()` actually although it wasn't an obvious thing to try for me.  Maybe something like `mgcv` syntax.  So in instead of `s(x,y, bs = ...)`, we have `my_component(main = c(x,y), model = ...)`.  No need for variable names to be strings in model formula so forget what I said about strings above.

**Comment by finnlindgren** [comment]
The `cbind` approach would still work with `lgcp()` for the `main=` parameter, but it becomes complicated when it tries to define the integration scheme, since that might currently require the `coordinates` keyword. You example seems like a very useful test case for figuring out alternative options for that.

The new backend code still needs more documentation, but `?component` is where it should show up soon/eventually. The `?component.character` documentation at least has the list of available arguments (but no useful documentation of them). In short, `main` takes an R expression that evaluates to where the latent variables should be evaluated (coordinates, indices, continuous scalar (for rw2 etc)). `mapper` is information about how to do the mapping. Currently it mostly auto-detects spde model objects in `model` and extracts the `mesh` object to use as the `mapper`, and auto-generates mappers for indexed models. `main_layer`/`main_selector` will be used to specify which variable in a spatial data frame (given to `main`) should be used. `n` is the number of latent variables in the model. Unclear at the moment for which models that can be safely autodetected; it gives an error if it can't figure it out by itself. Arguments starting with `weights`, `group`, `replicate` behave similarly to `main`, but for the corresponding features of `INLA::f`. That covers most of it...

**Comment by finnlindgren** [comment]
`c(x,y)` concatenates the variables into a longer vector, which is why you need `cbind(x,y)` instead. (I need to check if things break down with tibbles, since I know those can work a bit differently, but currently the variables exist as individual objects in the evaluation environment, so it should be fine.)
