### ISSUE TITLE
update gg.SpatialPolygons to identify holes

### ISSUE THREAD

**Issue by ASeatonSpatial** [fbachl/inlabru#95]
Currently a polygon with a hole is plotted like this when using the `gg` method

![image](https://user-images.githubusercontent.com/29274902/100858472-edcf1b80-3485-11eb-8f4b-e33f867222ff.png)

The disc is a hole but the plot treats it as it does the other polygons, it pays no attention to the hole logical variable that is included in the data.frame outputted by `fortify`.  

Replacing `geom_polygon` with `ggpolypath::geom_polypath` in the `gg.SpatialPolygons` function produces a plot like this:

![image](https://user-images.githubusercontent.com/29274902/100859109-c3319280-3486-11eb-9281-01529c5c3cef.png)

Seems like a simple enhancement so long as you are happy to take on the `ggpolypath` dependency.  I briefly looked for solutions using `geom_polygon` but this seems like someone has already solved the problem.

**Comment by finnlindgren** [comment]
Sounds good! Can you make a PR adding the new package as a `Suggests:`, and does `requireNamespace` on it in `gg.SpatialPolygons()`?

**Comment by ASeatonSpatial** [comment]
Sure happy to do that!

**Comment by finnlindgren** [comment]
Fixed by fb9b0b8c068f1c8264f719dc8ddb74fd7c4208e7
